made world control not crash when ic2 classic is installed
World-Control-Team/World-Control pull request #20
Opened 2019-01-18 21:23 UTC by Trinsdar

that is all I did when it comes to ic2 classic compat. I am not doing anything else in terms of that.
I did clean up he logic in Reactor utils as it was written in a very messy way and made it harder to read.
also I updated the forge version

2019-01-19 10:22 UTC, adrwa requested changes

2019-01-19 10:22 UTC, adrwa commented on build.gradle
> +	version = "1.12.2-14.23.5.2778"
Changing this stuff is out of scope for this PR

2019-01-19 10:22 UTC, adrwa commented on src/main/java/worldcontrolteam/worldcontrol/crossmod/industrialcraft2/ReactorUtils.java
> +        if (tile == null){
Please maintain the same format as the original

2019-01-19 10:22 UTC, adrwa commented on src/main/java/worldcontrolteam/worldcontrol/crossmod/industrialcraft2/ReactorUtils.java
> +        if (rStack.isEmpty()){
Please maintain the same format as the original

2019-01-19 10:22 UTC, adrwa commented on gradle.properties
> +mc_version=1.12.2
Changing this stuff is out of scope for this PR

2019-01-19 14:26 UTC, Trinsdar commented
Ok I'll change that back. The only reason I updated the forge version was because ic2 classic would crash with such old versions

2019-01-20 13:22 UTC, adrwa requested changes

2019-01-20 13:22 UTC, adrwa commented on build.gradle
> +	mappings = "snapshot_20171003"
This needs changing too

2019-01-21 03:00 UTC, adrwa approved these changes

2019-01-22 19:48 UTC, dmf444 commented
Haven’t checked myself, but the API changes, does that support all types of coolers and reactor components?

2019-01-23 01:47 UTC, Trinsdar commented
1. I have no idea
2. no it uses the same modid, although it also has a separate modid for checking for it specifically.

2019-01-23 02:03 UTC, Chocohead commented
Semantically it's a little different, `IReactorComponent` covers anything that can go in a reactor (`IBaseReactorComponent` covers anything that will be allowed to stay in a reactor, but not necessarily inserted). `AbstractDamageableReactorComponent` covers everything IC2 adds that can go in a reactor that also implements `ICustomDamageItem`, ie things that wear out or get charged up. Should be fine from the way it's being used there.

2019-03-24 04:46 UTC, merged